version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ibiskeycloak
    ports:
      - "11000:8443"
    environment:
      - KEYCLOAK_ADMIN=ibis
      - KEYCLOAK_ADMIN_PASSWORD=ibistest
    command:
      - start
      - --db=postgres
      - --features=token-exchange
      - --db-url=jdbc:postgresql://postgres:5432/database
      - --db-username=admin
      - --db-password=admin
      - --https-certificate-file=/etc/mosquitto/cert.pem
      - --https-certificate-key-file=/etc/mosquitto/privkey.pem

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
