version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      - my_network

  mqtt-broker:
    image: mqtt_broker:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - my_network
      

  python-server:
    image: auth_server:latest
    container_name: auth-python-server
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  my_network:
    driver: bridge
