version: '3'

services:
  mqtt-broker:
    image: mqtt_broker:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "8883:8883" # Secure MQTT port
    networks:
      - my_network
    volumes:
      - ./ca/ca-root-cert.crt:/mosquitto/certs/ca-root-cert.crt
      - ./ca/server.key:/mosquitto/certs/server.key
      - ./ca/server.crt:/mosquitto/certs/server.crt
      - ./mosquitto-config/go-auth.conf:/mosquitto/config/mosquitto.conf

networks:
  my_network:
    driver: bridge
